# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DataAwareMetadataEnricherPlugin
                                 A QGIS plugin
 Metadata extraction & enrichment using geospatial intelligence
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-02-11
        copyright            : (C) 2026 by MML
        email                : blessing.kavhu@maanmitauslaitos.fi
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DataAwareMetadataEnricherPlugin class from file DataAwareMetadataEnricherPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .data_aware_metadata_enricher import DataAwareMetadataEnricherPlugin
    return DataAwareMetadataEnricherPlugin(iface)

